/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 factory.gltf --transform
Files: factory.gltf [256.72KB] > C:\Users\MaroonStudios\Downloads\weekly_voxel_factory\factory-transformed.glb [203.21KB] (21%)
Author: elbriga (https://sketchfab.com/elbriga)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/weekly-voxel-factory-5bb999fe0ca84c4faa6149360268c32f
Title: Weekly Voxel Factory
*/

import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'

export default function Factory(props: GroupProps) {
  const { nodes, materials } = useGLTF('/factory-transformed.glb')
  return (
    <group {...props} dispose={null}>
      {/* @ts-expect-error @ts-ignore */}
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials['Scene_-_Root']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.125}
      />
    </group>
  )
}

useGLTF.preload('/factory-transformed.glb')
