/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 phone.gltf --transform
Files: phone.gltf [478.68KB] > C:\Users\MaroonStudios\Downloads\cell_phone\phone-transformed.glb [56.24KB] (88%)
Author: Matt Gilchrist (https://sketchfab.com/MattGilchrist)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cell-phone-793b092deff04d9fae3a368230bbc06f
Title: Cell Phone
*/

import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'

export default function Phone(props: GroupProps) {
  const { nodes, materials } = useGLTF('/phone-transformed.glb')
  return (
    <group {...props} dispose={null}>
      {/* @ts-expect-error @ts-ignore */}
      <mesh
        geometry={nodes.HomeButton_PhoneButtons_m_0.geometry}
        material={materials.PhoneButtons_m}
        position={[0, -1.322, -0.02]}
      />
      {/* @ts-expect-error @ts-ignore */}
      <mesh geometry={nodes.PhoneBody_PhoneBody_m_0.geometry} material={materials.PhoneBody_m} />
      {/* @ts-expect-error @ts-ignore */}
      <mesh
        geometry={nodes.PhoneBody_PhoneScreen_M_0.geometry}
        material={materials.PhoneScreen_M}
      />
    </group>
  )
}

useGLTF.preload('/phone-transformed.glb')
